-- Minimal shape for shared-code planner sync.
-- If your public.plans table already exists, most ALTER statements will be no-ops.

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  code text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.plans
  add column if not exists code text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.plans
set code = lower(trim(code))
where code is not null
  and code <> lower(trim(code));

alter table public.plans
  alter column code set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'plans_code_lowercase'
      and conrelid = 'public.plans'::regclass
  ) then
    alter table public.plans
      add constraint plans_code_lowercase
      check (code = lower(trim(code)));
  end if;
end $$;

create unique index if not exists plans_code_unique_idx
  on public.plans (code);

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_plans_updated_at on public.plans;
create trigger set_plans_updated_at
before update on public.plans
for each row
execute function public.set_row_updated_at();

alter table public.plans enable row level security;

grant select, insert, update on public.plans to anon;
grant select, insert, update on public.plans to authenticated;

drop policy if exists "plans_select_by_sync_code" on public.plans;
create policy "plans_select_by_sync_code"
on public.plans
for select
to anon, authenticated
using (
  code = lower(coalesce((current_setting('request.headers', true)::json ->> 'x-sync-code'), ''))
);

drop policy if exists "plans_insert_by_sync_code" on public.plans;
create policy "plans_insert_by_sync_code"
on public.plans
for insert
to anon, authenticated
with check (
  code = lower(coalesce((current_setting('request.headers', true)::json ->> 'x-sync-code'), ''))
);

drop policy if exists "plans_update_by_sync_code" on public.plans;
create policy "plans_update_by_sync_code"
on public.plans
for update
to anon, authenticated
using (
  code = lower(coalesce((current_setting('request.headers', true)::json ->> 'x-sync-code'), ''))
)
with check (
  code = lower(coalesce((current_setting('request.headers', true)::json ->> 'x-sync-code'), ''))
);
